name: Unit tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run tests on PHP 8.3
        uses: docker://php:8.3
        with:
          args: php tests.php

      - name: Run tests on PHP 7.0
        uses: docker://php:7.0
        with:
          args: php tests.php
